# Generated by Django 3.2.5 on 2022-02-06 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_hello_hellolucknum'),
    ]

    operations = [
        migrations.AddField(
            model_name='hello',
            name='hellomysentnce',
            field=models.TextField(default=0),
        ),
    ]
