# Generated by Django 3.2.5 on 2022-02-06 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_hello_hellomysentnce'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hello',
        ),
    ]
